name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Análise estática do código"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2023.1.7"
